apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-web-deployment
  labels:
    app: mi-web
spec:
  replicas: 2 # Kubernetes mantendrá siempre 2 copias de tu web funcionando
  selector:
    matchLabels:
      app: mi-web
  template:
    metadata:
      labels:
        app: mi-web
    spec:
      containers:
      - name: nginx-web
        image: dannymedinacoronel/mi-primera-app:latest # La imagen que acabas de subir
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mi-web-service
spec:
  type: NodePort # Esto expone la web en un puerto de tu servidor Debian
  selector:
    app: mi-web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080 # Podrás ver tu web en el puerto 30080